### ISSUE TITLE
Existence of model's getLabelAttr is implied in Tree.js

### ISSUE THREAD

**Issue by vvoovv** [pjekel/cbtree#10]
See line 512 of Tree.js
It shouldn't be implied

**Comment by pjekel** [comment]
Reference to implied method getLabelAttr() has been removed, the public model property 'labelAttr' is fetch directly instead, if one exists..

-----Original Message-----
From: Vladimir Elistratov [mailto:reply@reply.github.com] 
Sent: Thursday, April 12, 2012 4:08 PM
To: pjekel
Subject: [cbtree] Existence of model's getLabelAttr is implied in Tree.js (#10)

See line 512 of Tree.js
It shouldn't be implied

---

Reply to this email directly or view it on GitHub:
https://github.com/pjekel/cbtree/issues/10
