### ISSUE TITLE
Dojo 1.8: Uncaught TypeError: Object #<Object> has no method 'markProcessing' 

### ISSUE THREAD

**Issue by jmealo** [pjekel/cbtree#13]
Whenever I click on a tree item I get the following error:
Uncaught TypeError: Object #<Object> has no method 'markProcessing' 

I was able to add a markProcessing to the cbtree and that resolves clicking parent elements (method fires).

However, even with that in place, when you click child elements, the markProcessing error still occurs (it is called from dijit's tree.js).

When you comment out the relevant lines that call markProcessing() and unmarkProcessing() it gives an invalid item argument error.

Disabling deferItemLoadingUntilExpand in my ForestStoreModel didn't have an effect on these methods firing.

I'm using Dojo 1.8 and 1.5 on the same page.

Dojo 1.8 should be used for everything, but, I'm not sure if it's somehow interfering.

Thanks for all your hard work on cbtree!

Kudos,
Jeff

**Comment by pjekel** [comment]
Hi Jeff,

You are wondering into untested territories. DOJO claims you can use two different versions of DOJO  but it is something I haven't tested nor am I sure it applies to the same page. For your information, the 'markProcessing' method is a property of the TreeNode which cbtree inherits from the standard dijit tree. Also, the event handling for the TreeNode, that is for example clicking on it, has changed in dojo 1.8 and is not compatible with previous versions of dojo. 

To troubleshoot your issue I would recommend trying to load dojo 1.8 from an external source such as the Google CDN like in:

```
        <script src="//ajax.googleapis.com/ajax/libs/dojo/1.8.0/dojo/dojo.js"></script>
```

In this case are using an absolute URL to load dojo which will also guarantee all dojo modules will be loaded from the same location. Alternatively, run your app in debug mode and check were the browser loaded all your modules from. Also take a very close look at your 'dojoConfig' setting especially at the packages you defined.

**Comment by jmealo** [comment]
Thanks for the reply. I'll close this issue, there's way too many variables that could be at play here and it's not practical for me to debug at this time.
