### ISSUE TITLE
Contribute cbtree to dojox?

### ISSUE THREAD

**Issue by jankoprowski** [pjekel/cbtree#16]
Hi,

  I would like to use cbtree in project created by my company but I'm afraid this is 3rd party solution which may "die" in the future. Is there any reason why cbtree is not part of dojox package? Is there a chance to see cbtree in dojotookit?

Regards,

Jan

**Comment by pjekel** [comment]
Jan,

I have received the same questions many times and the answer is no. With dojo 2.0 the dojox namespace will cease to exist and will be removed from the dojo distribution therefore no new packages are accepted, please refer to https://dojotoolkit.org/reference-guide/1.8/dojox for more details.

All new dojo/dijit sub projects need to registered at http://packages.dojofoundation.org and are treated as stand-alone projects.

I have been maintaining the cbtree project for the last 3-4 years and will continue to do so. As a matter of fact in the next 2-3 weeks a new cbtree release will be made available with a whole set of new dojo/store API based stores and models, enhanced Tree styling, new demos and more. This new release supports both dojo 1.8 and 1.9 

You can already take a look at the documentation for this new release on the Wiki page at https://github.com/pjekel/cbtree/wiki

**Comment by jankoprowski** [comment]
Thank you for your response. Of course nothing stay forever but now I'm understanding why cbtree is separate project :) For me this explanation is really enough :) Thank You :) Issue is done for me :D

**Comment by pjekel** [comment]
It sounds like you are using a model intended for the cbtree/store or dojo/store with a legacy dojo/data store.
Demo cbtree/demo/data/tree12 you are referring to is based on the old dojo/data/ItemFileWriteStore which requires a model in the deprecated directory cbtree/models. (models -> plural)

Instead you are using a model from the cbtree/model directory (notice: model -> singular) which are intended for
the use with cbtree/store or dojo/store stores.

It is highly recommended, especially if you start a new project, to use the models in the cbtree/model directory
in combination with the stores in the cbtree/store directory.

Support for the legacy dojo/data store will be dropped in the near future.

Please checkout the installation instruction and directory structure:

https://github.com/pjekel/cbtree/wiki/Installation

**Comment by pjekel** [comment]
I'm don't know what dojo version you are using but the legacy dojo/data store do **_not_** have a query method whereas the newer dojo/store stores do. Therefore, if Dgrid calls query() you must use the new dojo/store stores.

I just looked at the Dgrid features and it clearly states it does not support dojo/data stores, checkout:

http://dojofoundation.org/packages/dgrid/

With regards to dojo/domReady, as the name implies, it fires when the DOM is ready that does not necessarily
mean dojo and all your modules have loaded. Use require() to wait for your modules as:

``` javascript
require([
    "cbtree/Tree", 
    "cbtree/model/TreeStoreModel", 
        ...
], function (Tree, Model, ... ) {

     // now do something....

});
```
