### ISSUE TITLE
I can't find the directory "cbtree/store/Hierarchy"

### ISSUE THREAD

**Issue by kinorsi** [pjekel/cbtree#17]
Hi,

In your wiki pages https://github.com/pjekel/cbtree/wiki/Store, demos come with directory for stores, but I can't find it. 

Regards,

Kinorsi

**Comment by pjekel** [comment]
Kinorsi,

The Wiki content is intended for the upcoming cbtree 0.9.3 release which will be available  when dojo 1.9 is released in the next 2-3 weeks. If you want to take a look at the code, including the new Hierarchy Store, select the dojo-1.9 branch instead of the master branch.

**Comment by kinorsi** [comment]
OH, I got it! Thank you!
