### ISSUE TITLE
Firefox: "too much recursion"

### ISSUE THREAD

**Issue by oliver-frietsch** [pjekel/cbtree#21]
When the tree exceeds a classic example size, Firefox 20.0.1 seems to reach its recursion limit. I initially couldn't believe that, but after turning on "extensions.firebug.showStackTrace" I saw a really impressive stack.
I've extended sample "00" to show the problem. I guess that a fix is difficult, as saving function calls might require design changes...

**Comment by oliver-frietsch** [comment]
Sorry, currently I don't have GIT access, and GitHub only seems to allow image attachments.
The example code is here:
http://pastebin.com/F3GT39bY

**Comment by pjekel** [comment]
The "too much recursion" issue is specific to Firefox and has not been fixed yet, see bug reports:

https://bugzilla.mozilla.org/show_bug.cgi?id=794427
https://bugzilla.mozilla.org/show_bug.cgi?id=832580

There are four work-arounds:

1 - Use Chrome, Safari or IE
2 - Assign every object a "checked" property as in:

```
{"name":"i128", "type":"continent", "checked":true}
```

2 - Set the model property "checkedAll" to false.
3 - Start using the new store cbtree stores and models available with the cbtree-v0.9.3 release.

The upcoming cbtree v0.9.3 release can be found at https://github.com/pjekel/cbtree/tree/dojo-1.9
