### ISSUE TITLE
Problem resizing the tree

### ISSUE THREAD

**Issue by evandrojr** [pjekel/cbtree#23]
Hi Pjekel,

I am unable to reduce the width of the tree. It always take all the entire width of the page. When I resize it, it breaks. Please, let me know if you can help me.

Thanks,
-Evandro

**Comment by pjekel** [comment]
Evando, checkout the wiki page:

https://github.com/pjekel/cbtree/wiki/CheckBox-Tree#wiki-checkbox-tree-placement

**Comment by evandrojr** [comment]
I am using like this:

<div align="center"   id="CheckboxTree" style="width:50px; height:300px; border-style:solid; border-width:medium;"></div> 

However nothing happens when I change the width. 

Thank you for the quick reply and for the excelent component. Well done!
