### ISSUE TITLE
Submiting  the checked nodes.

### ISSUE THREAD

**Issue by evandrojr** [pjekel/cbtree#24]
Hi Pjekel,

I would like to submit the id of the checked nodes. When I add the tree inside a form the values are not sent during Post. Is there a easy way to do it?

Many thanks,
-Evandro

**Comment by pjekel** [comment]
Evandro, only checkboxes that have a name are submitted in a POST, please see the following link for the solution:

http://www.thejekels.com/blog/featured/the-new-dijit-checkbox-tree/comment-page-1/#comment-630

**Comment by pjekel** [comment]
Evandro,

Just an update. The questions: <em>How do I submit Checkbox Tree checkboxes in a form?</em> kept popping up, I therefore added build-in support for checkbox submission. As of cbtree v0.9.4 the tree has an additional property called [attachToForm](https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-API#attachToForm) and an optional extension <em>TreeOnSubmit</em>.

Detailed information is available at:

[Checkboxes in HTML forms](https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-Usage#wiki-checkboxes-in-html-forms)
[Checkbox Tree in Forms](https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-in-Forms)

I would appreciate it if you could provide some feedback.

**Comment by evandrojr** [comment]
2013/10/29
pjekel notifications@github.com

> Checkboxes in HTML formshttps://github.com/pjekel/cbtree/wiki/CheckBox-Tree-Usage#wiki-checkboxes-in-html-forms

Dear pjekel,

I've read your wiki for that new feature and I like the simplicity of that.
Unfortunately, I have got no time to try it out at the moment. I am busy
working on that:
http://www.proofpoint.com/about-us/security-compliance-and-cloud-news/articles/brazil-announces-government-secure-email-program-522784

Thank you for keep improving that great tool that is the cbtree.

Well done!
