### ISSUE TITLE
IE10 RENDERING ISSUE

### ISSUE THREAD

**Issue by milanSch** [pjekel/cbtree#25]
Hi, 
It looks to be a problem with rendering in IE10. 
(Rendering in IE8, IE9, Firefox, Chrome work fine.)

Description:
1. Open page
http://www.thejekels.com/cbtree/demos/ 
(Dijit CheckBox Tree Demo v0.9.3)
in IE10 (version 10.0.9200.16540, update version 10.0.4)
1. Move cursor over check box (squares), check and uncheck checkBox. There is problem with rendering. Accidentally you can see checked box but it should be uncheck and vice versa. Also rendering of square around check box is not correct.

My workaround:
I have changed (overwrite) default class style

```
    .dijitCheckBoxInput
    {
        opacity: 0;
    }
```

from claro.css to

```
    .dijitCheckBoxInput
    {
        opacity: 0 !important;
    }
```

It works for me (IE8,IE9,IE10, Firefox 19.0.2, Chrome)

Thank you
milan

**Comment by pjekel** [comment]
It looks like the issue is specific to earlier versions of IE 10, I ran the test using IE Version 10.0.9200.16635 (update version 10.0.7) on Windows 7 and was not able to reproduce the problem.

**Comment by druizg** [comment]
Excelent, man...

You saved my life

thank you
