### ISSUE TITLE
dojo/store API support not working

### ISSUE THREAD

**Issue by Sudlon** [pjekel/cbtree#27]
I'm trying to get cbtree to work with the dojo/store API:

tree = new Tree({
                    model: new ForestStoreModel({
                          store: new Observable(new Memory()), 
                          rootId: "Root",
                          rootLabel: "Root",
                          childrenAttrs: ["children"]
                      }),
                    id: "treeWidget",
                }, "tree")

However, I keep getting the following error:
    Uncaught TypeError: Object [object Object] has no method 'getFeatures' 

, which is part of the old dojo/data API. Unfortunately, when I wrap the Observable Memory store in an ObjectStore:
    new ObjectStore({objectStore: storeMemory});

I get more errors:
    Uncaught TypeError: Object [object Object] has no method 'isValidated'

Am I doing something wrong, or is the dojo/store support not (fully) working?

PS When using the Dgrid with the storeMemory it works fine.
PPS I am using the "cbtree/store/Memory" for the Memory and the 'cbtree/models/ForestStoreModel' for the ForestStoreModel.

**Comment by Sudlon** [comment]
Ow, I forgot; I'm using
Dijit CheckBox Tree version 0.9.3, release date 05/03/2013 (dojo 1.8 & 1.9)

**Comment by pjekel** [comment]
Sudion,

For the cbtree to work correctly with the new dojo/store API you MUST use the tree models in the 'model' directory whereas you are trying to use the legacy tree models in the 'models' directory (notice the 's' at the end). For an example of an Observable dojo/store/Memory store please refer to https://github.com/pjekel/cbtree/blob/master/demos/store/tree01.html

In addition, before you decide to continue the use of Observable stores please take a look at: https://github.com/pjekel/cbtree/wiki/Store#important

Let me know if this works for you.

**Comment by pjekel** [comment]
One more tip, when I took a closer look at your sample I noticed the use of the 'childrenAttrs' property. The new dojo/store API stores are structured differently, that is, objects no longer have children, instead object's have a reference to their parent. As a result, you can't simply load ItemFileReadStore formatted data into a dojo/store store and expect the tree to work. If you must use legacy formatted data and still want to use the new dojo/store API take a look at the cbtree Hierarchy store and the IFRS data handler. An example can be found here: https://github.com/pjekel/cbtree/blob/master/demos/store/tree09.html

**Comment by Sudlon** [comment]
Thank you very much for your quick and very helpful response! By changing to the ForestStoreModel in the model-folder (no s!) it worked instantly!

Thank you as well for the tips! I actually don't use any hierarchy (yet), so I haven't  run into any trouble, but it is good to know beforehand in case I'll be working with it in the future!

Thanks again for your help!
