### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tcdaly** [pjekel/cbtree#32]
Thank you for this useful project. Regarding the installation instructions at https://github.com/pjekel/cbtree/wiki/Installation , the directory created when unzipping the package is actually called 'cbtree-master' not 'cbtree'.  So, I think those instructions should be updated.

**Comment by tcdaly** [comment]
I found that unless I renamed the folder 'cbtree-master' back to 'cbtree', the supplied demos didn't work due to 404 not found errors for certain javascript code.  If a decision has been made to rename 'cbtree' to 'cbtree-master', it looks like the rest of the code needs to be updated accordingly.

**Comment by pjekel** [comment]
It looks like you fetched the cbtree package directly from the Github master branch. If you use the [download](http://thejekels.com/download/cbtree) link instead and unzip the package it will actually create a directory like `/cbtree-v0.x.x`, this simply to avoid a newer cbtree version overwrite whatever you already have installed. After unzipping the package you SHOULD rename the newly created directory to `/cbtree` in order for the included demo's to work (See the alert in the Installation documentation).

I will include an extra note with regards to renaming the directory.

**Comment by pjekel** [comment]
Wiki documentation updated.
