### ISSUE TITLE
Tree sorting

### ISSUE THREAD

**Issue by bmnds** [pjekel/cbtree#34]
First of all, congratulations on making such a great component o/.

I'm currently trying to sort tree nodes as they are added to the tree but don't know where to start of. I've found 'SortDirective' at the QueryDirective and from what i've read it is used to query the store for the objects only. Even though it only sorts asc or desc based uppon an attribute.

What I need is to be able to provide a function that compares two Items, and the store would run this function against every children of the provided parent node (in the order they are currently being displayed at the tree). Basically this function would return -1, 0 or 1 and the function calls would stop when 0 or 1 get returned.

Can I achieve this with something already provided or at least can I have some guidance on how to implement it?

**Comment by pjekel** [comment]
I like the idea of being able to sort the tree node, and considering the cbtree infra structure already provided all the required functionality it was a simple enhancement.I also added a separate section on _SortIng Tree Nodes_ to the [cbtree Wiki](https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-Usage#wiki-sorting-tree-nodes) showing some examples on how to use the new model _options_ property.

I checked-in the enhancements so in order for you to give it a try please fetch the latest version from the [github repository](https://github.com/pjekel/cbtree) (no official download version available yet).

Please let me know if this works for you, I'll be waiting for your feedback before I compile an updated download version (e.g. cbtree-v0.9.4)

**Comment by bmnds** [comment]
That was really fast, thank you. 

I've tested the basic usage and it works smoothly. Just need some adjustments on the wiki page.
The options object definition is correct, but the examples are wrong:

```
      var options = {[
        {attribute: "name", descending: true, ignoreCase: true},
        {attribute: "hair", ignoreCase: true},
        {attribute: "age"}
      ]};
```

should be:

```
      var options = {sort: [
        {attribute: "name", descending: true, ignoreCase: true},
        {attribute: "hair", ignoreCase: true},
        {attribute: "age"}
      ]};
```

Now I'm trying to create a custom sorting function but I'm running into the following issue: whenever a function is passed as an element of the sort option, the tree renders only the first item. I've inspected the 'store' object after this error and all items were included.
Here is a test case for the issue:

```
      require([
        "dojo/ready",
        "cbtree/Tree",                     // Checkbox tree
        "cbtree/model/ForestStoreModel",   // Object Store Tree Model
        "cbtree/store/ObjectStore"         // Evented Object Store with Hierarchy
        ], function( ready, Tree, StoreModel, Store) {

        ready(function(){
            store  = new Store({idProperty:"name"});
            var options = { sort: [
                //{attribute: 'name'}
                function() { return 1 }
            ]}
            model  = new StoreModel({ store:store, query:{type:"PAI"}, options: options});
            tree   = new Tree( {model:model, showRoot:false, persist:false}, "tree" );
            tree.startup();

            loadData(store, data)
        })
      })
      var data = [
            { name: '1o PAI', type: 'PAI' },
            { name: '2o PAI', type: 'PAI' },
            { name: '11o PAI', type: 'PAI' }
        ]


      function loadData(store, data) {
        for (i in data) console.log('added '+store.add(data[i]))
      }
           }
```

NOTE: even though I've enabled dojo debug, whenever an error happens within the custom sorting function it doesn't throw anything, here is an example error generation function:

```
      function error(o) { return o.nonExistentProperty.length }
```

**Comment by pjekel** [comment]
Thanks for the feedback, I updated the Wiki examples as you recommended. Now for your example, the _options_ sort
property is either an array of sortInfo **_OR_** a function, not an array of functions. Therefore change your options to

``` javascript
var options = {sort: function () {return 1;}};
```

Remember, the options definition is as follows:

```
options     = "{" "sort" ":" sortOptions "}"
sortOptions = "[" sortInfo ["," sortInfo]* "]" / Function
sortInfo    = "{" attribute ["," descending] ["," ignoreCase] "}"
attribute   = "attribute" ":" JSidentifier
descending  = "descending" ":" boolean
ignoreCase  = "ignoreCase" ":" boolean
boolean     = "true" / "false"
```

With regards to error reporting, because cbtree and the associated dijit tree rely heavily on things like dojo/Deferred almost all exceptions are caught by dojo/Deferred.
However, any exception not handled by cbtree (dojo/Deferred) will show up in any debugger, the exception will be reported by dojo/promise/instrumentation.

Please let me know if this fixes your problem.
