### ISSUE TITLE
Parent-Child Relationship

### ISSUE THREAD

**Issue by abesk** [pjekel/cbtree#35]
Now, when I click on checkbox with "mixed" state, its and children value change to "true" state. I would like to set oposite. When I click on checkbox with "mixed" state, values will change to "false" state.

**Comment by pjekel** [comment]
If you want to change the checkbox toggle order you will have to change the Checkbox toggle() method. Change the following line in CheckBox.toggle(): 

``` javascript
return this._setCheckedAttr( (curState == 'mixed' ? true : !curState ) );
```

to:

``` javascript
return this._setCheckedAttr( (curState == 'mixed' ? !curState : true) );
```

**Comment by abesk** [comment]
thx
