### ISSUE TITLE
How to prevent onClick function calls if checkbox was clicked?

### ISSUE THREAD

**Issue by drnextgis** [pjekel/cbtree#41]
I need to call `onCheckBoxClick` function if checkbox was clicked and doesn't need to call `onClick` function in this case. `onClick` function should be invoked only if tree node was clicked (outside the checkbox area). How I can implement such behavior?

**Comment by pjekel** [comment]
Set the cbtree property **_clickEventCheckBox_** to `false` in which case clicking a checkbox will only call `onCheckBoxClick`. The default is `true`, which generates both the onClick and onCheckBoxClick events.

https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-API#clickeventcheckbox

**Comment by drnextgis** [comment]
Thanks!
