### ISSUE TITLE
how to set the checkbox to false in the tree?

### ISSUE THREAD

**Issue by ClementYap** [pjekel/cbtree#45]
Hi I would like to know how to set the checkbox  in the tree , to false programmatically?
The method  I used to read is like:-
 "registry.byID("tree").attr("selectedItem").checked = false".

Please advise what is the  right way?

**Comment by pjekel** [comment]
Try something like this

``` javascript
register.byId("tree").get("selectedItems").forEach(function (node) {
    node.set("checked", false);
});
```

**Comment by ClementYap** [comment]
Hi 
It does not work. With the highlighted node, 
I am not able to set this (leaf node) to false programmatically.
