### ISSUE TITLE
Unable to keep branch node expanded as long as there is a ticked leafcheck-boxes

### ISSUE THREAD

**Issue by ClementYap** [pjekel/cbtree#48]
Using 0.9.4
I was looking for solution to keep the branch node expanded if there are one ticked leaf checkboxe in the specified branch node.

using expandChecked(), is not working and I have read issue #36 and I am not able to make it.  

I have an array that keep track of item.id. As long as  the array is not empty, the branch node will not have to collapse

Please advise
 Thanks
Clement

**Comment by pjekel** [comment]
The Tree provides the required functionality for collapsing tree nodes by default. Please see [closeOnUnchecked](https://github.com/pjekel/cbtree/wiki/CheckBox-Tree-API#wiki-closeonunchecked) for details.

**Comment by ClementYap** [comment]
Hi I think I did not make myself clear. I was looking for how to make branch node gray amd disenable  if there are checked checkboxes in leaf nodes, unless there are no checked check boxes.
