### ISSUE TITLE
store shouldn't be exposed in cbtree/Tree

### ISSUE THREAD

**Issue by vvoovv** [pjekel/cbtree#5]
In the function postCreate .store property of this.model is exposed.
However the Tree class should be agnostic to implementation details of a Model instance. E.g. a Model class might not use store at all.

A check that a store supports dojo.data.api.Write should take place in cbtree/StoreModel

**Comment by pjekel** [comment]
You are correct, I'll move the store check to the model. In addition, I'll implement a check on the tree validating the model. If the underlying model has no means of maintaining the checked/checkbox states I could either disable the use of checkboxes or throw an error as the tree itself is completely unaware of the state associated with the checkboxes or their relationship.

-----Original Message-----
From: Vladimir Elistratov [mailto:reply@reply.github.com] 
Sent: Monday, April 02, 2012 4:31 AM
To: pjekel
Subject: [cbtree] store shouldn't be exposed in cbtree/Tree (#5)

In the function postCreate .store property of this.model is exposed.
However the Tree class should be agnostic to implementation details of a Model instance. E.g. a Model class might not use store at all.

A check that a store supports dojo.data.api.Write should take place in cbtree/StoreModel

---

Reply to this email directly or view it on GitHub:
https://github.com/pjekel/cbtree/issues/5
