### ISSUE TITLE
Disable processing bar when creating cbtree

### ISSUE THREAD

**Issue by bridgji** [pjekel/cbtree#52]
When I initially create the tree there seems to be an animate processing bar displayed while its being created. Is this something I can shut off ?  This is a image right before the tree appears.

![image](https://cloud.githubusercontent.com/assets/5721272/2607329/f5948c60-bb5b-11e3-9a1c-adf93a9faa7c.png)

**Comment by pjekel** [comment]
The process bar or load indicator is a characteristic of the dijit Tree, not the cbtree. If you want to disable this, locate the file `dijit/templates/Tree.html` which should look like:

``` html
<div role="tree">
    <div class="dijitInline dijitTreeIndent" style="position: absolute; top: -9999px;" data-dojo-attach-point="indentDetector"></div>
    <div class="dijitTreeExpando dijitTreeExpandoLoading" data-dojo-attach-point="rootLoadingIndicator"></div>
    <div data-dojo-attach-point="containerNode" class="dijitTreeContainer" role="presentation">
    </div>
</div>
```

Add `style="display:none"` to the class `dijitTreeExpando` is as:

``` html
<div class="dijitTreeExpando dijitTreeExpandoLoading" data-dojo-attach-point="rootLoadingIndicator" style="display:none"></div>
```

**NOTE:** Do NOT remove the `dijitTreeExpando` class as it has an attachment point. Also, you will have to make this change every time a newer version of dojo is installed.

**Comment by bridgji** [comment]
As always thank you for the quick response.
Instead of editing the tree.html I just added 
.dijitTreeExpando.dijitTreeExpandoLoading
{
    display:none;
}
 to my css style sheet and it seemed to do the trick.
