### ISSUE TITLE
Download Site

### ISSUE THREAD

**Issue by bridgji** [pjekel/cbtree#53]
I can't seem to get to the download site. Any idea when it might be back up?

Thanks

**Comment by pjekel** [comment]
The cbtree  website (thejekels.com) is currently experiencing network connectivity problems. To download the cbtree package, please refer to the cbtree releases section at:

https://github.com/pjekel/cbtree/releases

**Comment by pjekel** [comment]
The connectivity issues have been resolved, sorry for the delay
