### ISSUE TITLE
Checkboxes states for lazy loading mode

### ISSUE THREAD

**Issue by karavanjo** [pjekel/cbtree#56]
I initialize cbTree for lazy loading with FileStoreModel which has the parameter:
checkedStrict: false. As the data source use FileStore.
In my case, state of nested checkboxes don't affect to parental nodes. Likewise state of parental checkboxes don't affect to nested checkboxes.
If checkedStrict will have true value then cbTree will pull all nodes and leaves. This process may be very long.

How enable strict check for lazy loading mode without pulling all nested nodes?

**Comment by pjekel** [comment]
In order for the cbtree to properly determine the checked state of a parent it must know the checked state of all of its children (recursive) therefore, cbtree must load all children first. As a result, enabling checkedStrict will force all children to be loaded.
