### ISSUE TITLE
Function names getItem and setItem are confusing

### ISSUE THREAD

**Issue by vvoovv** [pjekel/cbtree#6]
In fact those function are getting/setting an item attribute.

I'd suggest to rename them to getItemAttr and setItemAttr respectively

**Comment by pjekel** [comment]
Agreed, I will made the changes.

-----Original Message-----
From: Vladimir Elistratov [mailto:reply@reply.github.com] 
Sent: Monday, April 02, 2012 4:39 AM
To: pjekel
Subject: [cbtree] Function names getItem and setItem are confusing (#6)

In fact those function are getting/setting an item attribute.

I'd suggest to rename them to getItemAttr and setItemAttr respectively

---

Reply to this email directly or view it on GitHub:
https://github.com/pjekel/cbtree/issues/6
