### ISSUE TITLE
Make model validation code in cbtree/Tree more consistent

### ISSUE THREAD

**Issue by vvoovv** [pjekel/cbtree#9]
Now we have in the cbtree/Tree:
this.connect(model, "onStoreComplete", "_onModelValidated");
model._validateData();

I'd suggest:
this.connect(model, "onDataValidated", "_onModelValidated");
model.validateData();

So I propose to rename in the cbtree/StoreModel
onStoreComplete -> onDataValidated
_validateData -> validateData

**Comment by pjekel** [comment]
Agreed and done.

-----Original Message-----
From: Vladimir Elistratov [mailto:reply@reply.github.com] 
Sent: Monday, April 09, 2012 5:45 AM
To: pjekel
Subject: [cbtree] Make model validation code in cbtree/Tree more consistent (#9)

Now we have in the cbtree/Tree:
this.connect(model, "onStoreComplete", "_onModelValidated"); model._validateData();

I'd suggest:
this.connect(model, "onDataValidated", "_onModelValidated"); model.validateData();

So I propose to rename in the cbtree/StoreModel onStoreComplete -> onDataValidated _validateData -> validateData

---

Reply to this email directly or view it on GitHub:
https://github.com/pjekel/cbtree/issues/9
